title: JennyLab Blog
description: El blog de JennyLab 
baseurl: ""
url: "https://jennylab.info"
repository: jennylab.github.io

ssl_certificate: /lib/tasks/c3rty.crt
ssl_certificate_key: /lib/tasks/c3rty.key


remote_theme: just-the-docs/just-the-docs

permalink: pretty

defaults:
  - scope:
      path: "docs"
      type: "pages"
    values:
      layout: "default"

exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - bin/
  - lib/
  - "*.gemspec"
  - "*.gem"
  - LICENSE.txt
  - package.json
  - package-lock.json
  - Rakefile
  - README.md
  - CODE_OF_CONDUCT.md
  - docker-compose.yml
  - Dockerfile
  - fixtures/

search_enabled: true
search:
  heading_level: 2
  previews: 2
  preview_words_before: 3
  preview_words_after: 3
  tokenizer_separator: /[\s/]+/
  rel_url: true
  button: false
  focus_shortcut_key: "k"

enable_copy_code_button: true

mermaid:
  version: "9.1.6"

heading_anchors: true

aux_links:
  "Just the Docs on GitHub":
    - "https://github.com/just-the-docs/just-the-docs"

aux_links_new_tab: false

nav_enabled: true
nav_sort: case_sensitive

nav_external_links:
  - title: Just the Docs on GitHub
    url: https://github.com/just-the-docs/just-the-docs

nav_error_report: true

liquid:
  error_mode: strict
  strict_filters: true

back_to_top: true
back_to_top_text: "Back to top"

footer_content: 'Public Domain &copy; (JennyLab) '

last_edit_timestamp: true
last_edit_time_format: "%b %e %Y at %I:%M %p"

gh_edit_link: true
gh_edit_link_text: "Edit this page on GitHub"
gh_edit_repository: "https://github.com/jennylab/jennylab.github.io"
gh_edit_branch: "main"
gh_edit_view_mode: "tree"

color_scheme: nil

callouts_level: quiet
callouts:
  highlight:
    color: yellow
  important:
    title: Important
    color: blue
  new:
    title: New
    color: green
  note:
    title: Note
    color: purple
  warning:
    title: Warning
    color: red

plugins:
  - jekyll-seo-tag
  - jekyll-github-metadata
  - jekyll-include-cache
  - jekyll-sitemap

kramdown:
  syntax_highlighter_opts:
    block:
      line_numbers: false

compress_html:
  clippings: all
  comments: all
  endings: all
  startings: []
  blanklines: false
  profile: false
